---
title: "Collecting and Analyzing Web Data - First Project"
author: "Fill in your name"
output: html_document
date: "last updated: `r Sys.Date()`"
---


*In groups of around 3-5 people, fill out this sheet on current debates about scraping, its scientific use and doing research in R. When you are finished, upload your solutions on GitHub.*

\setcounter{tocdepth}{2}
\tableofcontents

## Introduction

### GitHub

Your GitHub account:
/mmbch

### Previous experience

Fill in this [short survey on your previous experience](https://forms.gle/BJtFLNVWirnDWzSZ8)


\pagebreak


## Legal regulations and hacktivism

### Legality of scraping


Describe what the following terms / laws / cases refer to in one sentence each:

terms of service: are legal agreements between a service provider and a person who wants to use that service.

GDPR: a regulation in EU law on data protection and privacy in the European Union (EU) and the European Economic Area (EEA). 

Computer Fraud and Abuse Act: is a United States cybersecurity bill that was enacted in 1986 as an amendment to existing computer fraud law.

Sandvig v. Barr: The ACLU has filed a lawsuit challenging the constitutionality of the Computer Fraud and Abuse Act, which makes it a federal crime to access a computer in a manner that “exceeds authorized access.”



### Terms of service

Something that is not allowed: You may not do any of the following while accessing or using the Services: (i) access, tamper with, or use non-public areas of the Services, Twitter’s computer systems, or the technical delivery systems of Twitter’s providers; (ii) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures; (iii) access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by Twitter (and only pursuant to the applicable terms and conditions), unless you have been specifically allowed to do so in a separate agreement with Twitter

Something that is confusing: We may suspend or terminate your account or cease providing you with all or part of the Services at any time for any or no reason, including, but not limited to, if we reasonably believe: (i) (...), (ii) you create risk or possible legal exposure for us; (...)

Something related to scraping: access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by Twitter (and only pursuant to the applicable terms and conditions), unless you have been specifically allowed to do so in a separate agreement with Twitter (NOTE: crawling the Services is permissible if done in accordance with the provisions of the robots.txt file, however, scraping the Services without the prior consent of Twitter is expressly prohibited)


### robots.txt


webpage you checked: https://twitter.com/robots.txt


### Hacktivism

Find information about the following people.

- Aaron Swartz (US)
  - RSS, Markdown, Co-Founder of Reddit, PACER, JSTOR, suicide with 26yrs
- Alexandra Elbakyan (KZ)
  - Sci-Hub (free access to research papers)
- Karrie Karahalios (US)
  - noted for her work on the impact of computer science on people and society, analyses of social media, and algorithm auditing
- Murray Cox (AU)
  - runs Inside Airbnb, which uses the startup’s own data to highlight illegal listings in big cities
- Paolo Cirio (IT)
  - exposed over 200,000 Cayman Islands offshore firms with the work Loophole for All in 2013
  - the hacking of Facebook through publishing 1 million users on a dating website with Face to Facebook in 2011
  - cyber attacks against NATO
- another data activist of your choosing


### Scientific debate

article:

author's position:

\pagebreak


## Scientific use of scraping

### Use of scraping

Number of results:

Search terms:

### An article that uses webscraped data


article:

How is web data relevant:

### Your ideas for scraping

page:

idea:


\pagebreak


## Course practicalities

### Coding Style


Which tutorial / style guide did you look at?

One thing you want to improve about your R code:

One thing you disagree with:

### Coding for others



Which coding / style decisions were the most contested within your group?



### Work environment

How did you structure your folder?



### Submit!
